language: shell
git:
  depth: 50
  quiet: true
  submodules: false
os:
  - linux
#python:
#  - "2.7"
dist: xenial
before_script:
  # Set up git user name and tag this commit
  - git config --global user.name "xiaoluhong"
  - git config --global user.email "xiaoluhong@rancher.com"
  - git config --global push.default simple

script:
#  - bash docs2_update_file.sh
#  - bash website_update_file.sh
  - cron_update_repo.sh

before_install:
  - sudo apt-get install jq curl >> /dev/null
  - chmod +x docs2_update_file.sh website_update_file.sh cron_update_repo.sh