# 定时更新 xiaoluhong/k3s-sync 查看下的 update.txt 文件，来触发 https://travis-ci.com/github/xiaoluhong/k3s-sync 构建。

name: file_k3s-sync

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */5 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          TZ: 'Asia/Shanghai'
        run: |
          git config --global push.default matching
          git config --global pull.ff only
          git config --local user.email "xiaoluhong@rancher.com"
          git config --local user.name "xiaoluhong"
          bash cron_sync-file_k3s-sync.sh
