name: rancher-v215-latest-images-dockerhub-to-aliyun

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        env:
          ALIYUN_ACC: ${{ secrets.ALIYUN_ACC }}
          ALIYUN_PW: ${{ secrets.ALIYUN_PW }}
          TZ: 'Asia/Shanghai'
        run: |
          bash -x rancher-v215-latest-images-dockerhub-to-aliyun.sh